### ISSUE TITLE
Corrupt?

### ISSUE THREAD

**Issue by ineuw** [ianwremmel/browser-ruler#77]
I am using FF 52.9.0 ESR and I got a message that the add-on is corrupt. 

![rulercorrpt](https://user-images.githubusercontent.com/10367016/44371419-da623700-a4ac-11e8-97f4-db475b012fd6.jpg)

**Comment by ianwremmel** [comment]
That's weird. I'm traveling at the moment, but I'll try to look into this in the coming weeks.

**Comment by ineuw** [comment]
It is not a corruption in the add-on. There is something blocking it in
Firefox. This is noted by other users of Firefox and can be found on the
web. I believe Cyberfox mentions a fix.

ineuw

P.S: I am using both Firefox ESR and Cyberfox to test legacy add-on
compatibility and other issues.

**Comment by ianwremmel** [comment]
Ok, so, can this issue be closed?

**Comment by ineuw** [comment]
The ruler https://addons.mozilla.org/en-US/firefox/addon/browser-ruler/ is broken but now the message is "Download failed. Please check your connection." So, I gave up. Please don't bother on my account, I found something else. On the other hand, why don't you pull the add-on? Why frustrate users who are attempting to download it??

**Comment by ianwremmel** [comment]
I apologize for not investigating sooner.  Based on your previous messages, I was under the impression you had determined the problem to be related to your environment and not to this extension. 

> On the other hand, why don't you pull the add-on? Why frustrate users who are attempting to download it??

I just checked and I was able to download it successfully with the current version of Firefox, so I don't see any reason to pull it at this time.

**Comment by ineuw** [comment]
Sorry for not mentioning that I use the legacy FF52.9 ESR version of
Firefox. With legacy versions earlier than FF57 the import doesn't work.

**Comment by ianwremmel** [comment]
ah, ok, that explains it. This is an extension I originally wrote for Chrome and adjusted for Firefox when Firefox adopted the web extension API. 

https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
https://wiki.mozilla.org/WebExtensions/FAQ#When_did_Firefox_adopt_the_WebExtensions_API.3F

I don't believe it's feasible at this time to support browser versions that don't support Web Extensions.

**Comment by ineuw** [comment]
Thanks for the explanation. At the time I had no clue, and went by the enabled "Install" button.
